### ISSUE TITLE
type mapping gets lost because DatabaseManager between classes is not the same

### ISSUE THREAD

**Issue by michabbb** [krlove/eloquent-model-generator#97]
hi, it took me a while but for me it looks like a bug.
the changelog says that "enum" gets registered by default.
but when I see the code, it seems like nothing gets registered if "db_types" is not set in the config.

https://github.com/krlove/eloquent-model-generator/blob/2x/src/EventListener/GenerateCommandEventListener.php#L23

secondly, more important: 

even if "db_types" is used in the config, it gets set here in the code, **BUT**  because a fresh new "DatabaseManager" gets resolved here: 

https://github.com/krlove/eloquent-model-generator/blob/2x/src/Processor/RelationProcessor.php#L17

this new `$schemaManager` no longer knows about any types that have been set in `GenerateCommandEventListener.php`.

so right now I am forced to add 

`$schemaManager->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');`

in line 22 to make "enum" working.

**Comment by krlove** [comment]
Hi @michabbb , thank you for submission of this bug, nice catch! I've fixed this in this release https://github.com/krlove/eloquent-model-generator/releases/tag/2.0.1

**Comment by denes096** [comment]
Hello, I am still facing with this issue, even if i downloaded the 2.0.1 version. The $schemaManager->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string'); line added to RelationProcessor #22 solved the issue.

**Comment by michabbb** [comment]
@krlove your commit for tag 2.0.1 does not show any modification to any PHP file, so I guess you missed something here, because as @denes096 said, this issue is not yet fixed, sorry.
